meta_product_name: "Luma"
meta_title: "Luma - La plateforme des avantages des employés"
meta_description: "Luma propose une application pour les employés des startups avec les meilleurs avantages: culture, sport, voyages.."
meta_image: "logo_luma_white.png" # should exist in `app/assets/images/`
